# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Catatan Ivan Achlaqullah
email:
description: >- # this means to ignore newlines until "baseurl:"
  Blog milik Ivan Achlaqullah
twitter_username: ivanachlaqullah
github_username: ivan_achlaqullah
name: "Ivan Achlaqullah"
minimal_mistakes_skin: contrast
search: true
logo: /assets/images/logo-ivan.png
og_image: /assets/images/logo-ivan.png

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 10 # amount of posts to show
paginate_path: /page:num/
timezone: Asia/Jakarta # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Ivan Achlaqullah"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Programmer & 3D Artist."
  location: "Jakarta, Indonesia"
  links:
    - label: "Mastodon"
      icon: "fab fa-fw fa-mastodon"
      url: "https://ohai.social/@ivan_achlaqullah"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/ivanachlaqullah"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/ivan-achlaqullah"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ivan_achlaqullah"
    - label: "GitLab"
      icon: "fab fa-fw fa-gitlab"
      url: "https://gitlab.com/ivan_achlaqullah"

footer:
  links:
    - label: "Mastodon"
      icon: "fab fa-fw fa-mastodon"
      url: "https://ohai.social/@ivan_achlaqullah"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/ivanachlaqullah"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/ivan-achlaqullah"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ivan_achlaqullah"
    - label: "GitLab"
      icon: "fab fa-fw fa-gitlab"
      url: "https://gitlab.com/ivan_achlaqullah"

comments:
  provider: "disqus"
  disqus:
    shortname: "catatan-ivan-achlaqullah"

analytics:
  provider: "custom"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      show_date: true
      date_format: "%-d %B %Y"
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
